version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
  
  django:
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
